apiVersion: v1
kind: Pod

metadata:
  name: jenkins-nfs-pv-pod

spec:
  volumes:
    - name: jenkins-nfs-pv-storage
      persistentVolumeClaim:
        claimName: jenkins-nfs-pv-claim

  containers:

    - name: jenkins-nfs-pv-container

      image: ubuntu
      command:
      - "sleep"
      - "604800"
      resources:
        limits:
          memory: "2Gi"
          cpu: "1000m"
        requests:
          memory: "500Mi"
          cpu: "500m"



      volumeMounts:
        - mountPath: "/usr/share/jenkins"
          name: jenkins-nfs-pv-storage




