apiVersion: v1

kind: PersistentVolume
metadata:
  name: jenkins-nfs-pv-volume
  # labels:
  #   type: local

spec:
  storageClassName: nfs

  capacity:
    storage: 10Gi

  accessModes:
    - ReadWriteOnce
  
  # mountOptions:
  #   - nfsvers=4.1
  
  nfs:
    path: "/mnt/jenkins"
    # server: 172.23.190.164
    server: ubuntu