apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: ubuntu
    command:
    - "sleep"
    - "604800"  
    name: test-container
    resources:
      limits:
        memory: "2Gi"
        cpu: "1000m"
      requests:
        memory: "500Mi"
        cpu: "500m"    
    volumeMounts:
    - mountPath: /test-pd
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      # directory location on host
      path: /mnt/jenkins