apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-inner-steps
spec:
  templates:
  - name: inner-steps
    inputs:
      parameters:
      - name: message
        value: default   
    steps:
    - - name: inner-step2
        # when: "[{{inputs.parameters.message}}] =~ second"
        templateRef:
          name: workflow-template-python-template
          template: print-message
        arguments:
          parameters:
          - name: message
            value: "{{inputs.parameters.message}}"

    - - name: inner-step1
        # when: "[{{inputs.parameters.message}}] =~ first"
        templateRef:
          name: workflow-template-whalesay-template
          template: whalesay-template
        arguments:
          parameters:
          - name: message
            value: {{step.inner-step2.output.results}}


