
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-inner-steps
spec:
  templates:
  
  - name: whalesay-template
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]
  
  - name: print-message
    inputs:
      parameters:
      - name: message
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo result was: {{inputs.parameters.message}}"]

  - name: inner-steps

    steps:

    - - name: inner-hello1 
        when: "'{{arguments.message.value}}' =~ 'first'"
        templateRef:
          name: workflow-template-whalesay-template
          template: whalesay-template      
        arguments:
          parameters:
          - name: message
            value: "inner-hello1"        
        

    - - name: inner-hello2
        when: "'{{arguments.message.value}}' =~ 'second'"        
        templateRef:
          name: workflow-template-python-template
          template: print-message
        arguments:
          parameters:
          - name: message
            value: "inner-hello2"
